spring:
  application:
    name: "AuthMax"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    remote:
      secret: changeme  # Mesmo valor definido no compose